In [9]:
import os 
import os.path
import pandas as pd 
import numpy as np
import pickle 
import torch

from google.colab import drive
drive.mount("/content/drive", force_remount=True)


Mounted at /content/drive


In [10]:
with open("drive/MyDrive/OrlyPred/Homomer_embeds/results/embeds_Dec22_esm2/embed_pkl_chunk2513", 'rb') as f:
  chunk2513 = pickle.load(f)
chunk2513

[tensor([ 0.0181, -0.0911, -0.0765,  ..., -0.1937, -0.0622,  0.0596]),
 tensor([ 0.0176, -0.0945, -0.0752,  ..., -0.1990, -0.0593,  0.0612]),
 tensor([ 0.0183, -0.0914, -0.0770,  ..., -0.1919, -0.0631,  0.0581]),
 tensor([-0.0223, -0.1072,  0.0413,  ..., -0.1062, -0.1469, -0.0024]),
 tensor([ 0.0997, -0.0774,  0.0082,  ..., -0.1683,  0.0076,  0.0556]),
 tensor([ 0.0418,  0.0428, -0.0101,  ..., -0.2157, -0.0515,  0.0850]),
 tensor([ 0.0365, -0.0507, -0.0200,  ..., -0.1561,  0.0358,  0.0364]),
 tensor([-0.0087,  0.0009, -0.0358,  ..., -0.1240, -0.0800,  0.0605]),
 tensor([ 0.0349, -0.0823, -0.0209,  ..., -0.1029, -0.0081,  0.0830]),
 tensor([ 0.0359, -0.0846, -0.0188,  ..., -0.1039, -0.0090,  0.0800])]

In [ ]:
with open("drive/MyDrive/OrlyPred/Homomer_embeds/results/embeds_Mar_22/parsed_tab_for_embed.pkl", 'rb') as f:
  full_tab_for_embed = pickle.load(f)
full_tab_for_embed.reset_index(inplace=True, drop=True)
print(full_tab_for_embed)

In [33]:
for i, ten in enumerate(chunk2513):
  ten=ten.detach().numpy()
  print(type(ten))
  df.at[i, 0] = ten
df


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


0
0  [0.018128674, -0.091121696, -0.0765239, 0.0468...
1  [0.017580124, -0.09450639, -0.075179085, 0.050...
2  [0.018271467, -0.09143638, -0.07700555, 0.0476...
3  [-0.022289142, -0.10723377, 0.041327126, 0.013...
4  [0.099717386, -0.07736629, 0.008178875, -0.017...
5  [0.0418162, 0.042803362, -0.010067892, 0.02053...
6  [0.03648698, -0.050741684, -0.019969253, -0.05...
7  [-0.008680201, 0.0009059226, -0.0357893, 0.012...
8  [0.03492461, -0.08230902, -0.02088546, 0.04533...
9  [0.03592981, -0.08456183, -0.018779993, 0.0425...